Name:           ros-hydro-screenrun
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS screenrun package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/screenrun
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-roscpp
Requires:       screen
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-roscpp

%description
screenrun is a small tool that pushes commands into a screen window. Use \015
after a command for ENTER, i.e. executing it.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Wed Feb 04 2015 Christian Dornhege <c.dornhege@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

* Thu Jan 29 2015 Christian Dornhege <c.dornhege@gmail.com> - 1.0.1-0
- Autogenerated by Bloom

